version: 0.2
phases:
   install:
      runtime-versions:
         docker: 18
   pre_build:
      commands:
      - echo "Entered the pre-build phase"
      - $(aws ecr get-login  --no-include-email --region $AWS_REGION)
   build:
      commands:
      - echo "Entered build phase"
      - cd SubscriptionService
      - mvn compile
      - mvn package
      - echo " building docker image"
      - docker build -t service/subsapp .
      - docker tag service/subsapp 430321133782.dkr.ecr.us-east-1.amazonaws.com/j008-pod7-subscriptionrepo-ecr:subsapp
   post_build:
      commands:
      - echo "Entered the post-build phase"
      - docker push 430321133782.dkr.ecr.us-east-1.amazonaws.com/j008-pod7-subscriptionrepo-ecr:subsapp
      - printf '[{"name":"subsapp-container","imageUri":"%s"}]' 430321133782.dkr.ecr.us-east-1.amazonaws.com/j008-pod7-subscriptionrepo-ecr:subsapp>taskdefinition.json
artifacts:
   files:
   - SubscriptionService/taskdefinition.json