INSERT INTO DRUG_DETAILS VALUES ('D1', 'Drug1', parsedatetime('22-11-2024', 'dd-MM-yyyy'), parsedatetime('22-22-2020', 'dd-MM-yyyy'), 'manu1');
INSERT INTO DRUG_DETAILS VALUES ('D2', 'Drug2', parsedatetime('22-11-2024', 'dd-MM-yyyy'), parsedatetime('22-22-2020', 'dd-MM-yyyy'), 'manu2');
INSERT INTO DRUG_DETAILS VALUES ('D3', 'Drug3', parsedatetime('22-11-2024', 'dd-MM-yyyy'), parsedatetime('22-22-2020', 'dd-MM-yyyy'), 'manu3');

INSERT INTO DRUG_LOCATION_DETAILS VALUES('1', 'Chennai', 30, 'D1');
INSERT INTO DRUG_LOCATION_DETAILS VALUES('2', 'Bangalore', 20, 'D1');
INSERT INTO DRUG_LOCATION_DETAILS VALUES('3', 'Pune', 30, 'D1');
INSERT INTO DRUG_LOCATION_DETAILS VALUES('4', 'Hydrabad', 30, 'D1');
INSERT INTO DRUG_LOCATION_DETAILS VALUES('5', 'Chennai', 30, 'D2');
INSERT INTO DRUG_LOCATION_DETAILS VALUES('6', 'Bangalore', 20, 'D2');
INSERT INTO DRUG_LOCATION_DETAILS VALUES('7', 'Pune', 30, 'D2');
INSERT INTO DRUG_LOCATION_DETAILS VALUES('8', 'Hydrabad', 30, 'D2');
INSERT INTO DRUG_LOCATION_DETAILS VALUES('9', 'Chennai', 30, 'D3');
INSERT INTO DRUG_LOCATION_DETAILS VALUES('10', 'Bangalore', 20, 'D3');
